#%RAML 1.0
title: Social Media - Twitter Management System

baseUri: sc37-twittermanagement-sys.us-e2.cloudhub.io/api/twitter/v1

description: The Twitter Management System API allows a user to filter through tweets and hashtags while only returning core pieces of important information, for use of social media analysis.

protocols:
  - HTTPS
version: 1.0


traits:
  client-id-required:
    headers:
      client_id:
        type: string
      client_secret:
        type: string

/tweets:
    get:
      description: This endpoint is used to return tweets that contain the given {searchCriteria}, that have been created in the past {timeLimit} hours.
      is: [ client-id-required]
      queryParameters:  
        searchCriteria:
          type: string
          description: The search string that should be present in each tweet returned.
          required: true
          example: "Chicago Bears"

        timeLimit:
          type: integer
          description: The timeLimit parameter filters the search so that only tweets that have been created in the past {timeLimit} hours are returned.\
          required: true
          example: 5
        
        resultSize:
          type: integer
          description: The resultSize parameter limits the number of tweets that are returned in the response. This parameter has a maximum of 10 and defaults to the maximum if not given.
          required: false
          example: 10

      responses:
        200:
          body:
            application/json:
              type: object
              example: !include examples/filtered-tweets.json

    /popular/hashtags:
      get:
        description: This endpoint is used to return a list of unique hashtags used in the top 10 most popular tweets that include the given {searchCriteria}.
        is: [ client-id-required]
        queryParameters:  
          searchCriteria:
            type: string
            description: The search string that should be present in each tweet that the hashtags belong to.
            required: true
            example: "tiktok"

        responses:
          200:
            body:
              application/json:
                type: object
                example: !include examples/hashtags-from-popular-tweets.json
      
              
